version: '3.9'
services:
  neo4j:
    image: neo4j:5.26
    container_name: neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"   # Browser
      - "7687:7687"   # Bolt (protocollo per Cypher)
    environment:
      NEO4J_AUTH: neo4j/password1234
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_dbms_connector_bolt_advertised__address: localhost:7687
    volumes:
      - ./data:/var/lib/neo4j/import
    healthcheck:
      test: [ "CMD", "cypher-shell", "-u", "neo4j", "-p", "password1234", "RETURN 1" ]
      interval: 15s
      timeout: 20s
      retries: 15
  seed:
    image: neo4j:5.26
    container_name: neo4j-seed
    depends_on:
      neo4j:
        condition: service_healthy
    volumes:
      - ./scripts/neo4j:/init
      - ./data:/var/lib/neo4j/import
    entrypoint: >
      bash -c "
        until cypher-shell -a bolt://neo4j:7687 -u neo4j -p password1234 'RETURN 1'; do
          echo 'Waiting for Neo4j to be ready...';
          sleep 3;
        done;
        echo 'Creating Counties';
        cypher-shell -a bolt://neo4j:7687 -u neo4j -p password1234 -f /init/create_counties.cypher;
        echo 'Creating Tornadoes';
        cypher-shell -a bolt://neo4j:7687 -u neo4j -p password1234 -f /init/create_tornadoes.cypher;
        echo 'Creating Traces';
        cypher-shell -a bolt://neo4j:7687 -u neo4j -p password1234 -f /init/create_traces.cypher;
        echo 'Creating new links to Counties';
        cypher-shell -a bolt://neo4j:7687 -u neo4j -p password1234 -f /init/create_links_counties.cypher;
        echo 'Finished seeding the database.';
      "
