version: '3.8'
services:
  neo4j:
    image: neo4j:5.19
    container_name: neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"   # Browser
      - "7687:7687"   # Bolt (protocollo per Cypher)
    environment:
      NEO4J_AUTH: neo4j/password123
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_dbms_connector_bolt_advertised__address: localhost:7687
    volumes:
      - ./data:/var/lib/neo4j/import
      - ./scripts/init_ne4j.cypher:/docker-entrypoint-initdb.d/init_ne4j.cypher
