
CREATE TABLE IF NOT EXISTS tsunami (
    id INTEGER PRIMARY KEY,
    eventDate TIMESTAMP,
    eventValidity VARCHAR(50),
    causeCode VARCHAR(50),
    earthquakeEventId VARCHAR(50),
    volcanoEventId VARCHAR(50),
    country VARCHAR(50),
    locationName VARCHAR(255),
    regionCode VARCHAR(50),
    latitude FLOAT,
    longitude FLOAT,
    eqMagnitude FLOAT,
    eqDepth FLOAT,
    maxWaterHeight FLOAT,
    tsIntensity FLOAT,
    tsMtIi FLOAT,
    tsMtAbe FLOAT,
    deaths INTEGER,
    deathsTotal INTEGER,
    injuries INTEGER,
    injuriesTotal INTEGER,
    missing INTEGER,
    missingTotal INTEGER,
    housesDestroyed INTEGER,
    housesDestroyedTotal INTEGER,
    housesDamaged INTEGER,
    housesDamagedTotal INTEGER,
    damageMillionsDollars FLOAT,
    damageMillionsDollarsTotal FLOAT,
    numRunups INTEGER,
    numDeposits INTEGER,
    area VARCHAR(50),
    publish BOOLEAN,
    oceanicTsunami BOOLEAN,
    warningStatusId VARCHAR(50),
    regionName VARCHAR(255),
    cause VARCHAR(255),
    validity VARCHAR(255),
    warningStatus VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);