
CREATE TABLE IF NOT EXISTS eruptions (
    damageAmountOrder VARCHAR(50),
    earthquakeEventId INTEGER,
    eruption BOOLEAN,
    housesDestroyed VARCHAR(50),
    injuries VARCHAR(50),
    location VARCHAR(255),
    longitude FLOAT,
    missing VARCHAR(50),
    name VARCHAR(255),
    position_type VARCHAR(50),
    publish BOOLEAN,
    significant BOOLEAN,
    timeErupt VARCHAR(255),
    tsunamiEventId INTEGER,
    vei VARCHAR(50),
    year INTEGER,
    agent VARCHAR(255),
    damageAmountOrderTotal VARCHAR(50),
    housesDestroyedAmountOrder VARCHAR(50),
    injuriesAmountOrder VARCHAR(50),
    missingAmountOrder VARCHAR(50),
    status VARCHAR(50),
    volcano_id INTEGER,
    country VARCHAR(100),
    damageMillionsDollars VARCHAR(50),
    housesDestroyedAmountOrderTotal VARCHAR(50),
    injuriesAmountOrderTotal VARCHAR(50),
    missingAmountOrderTotal VARCHAR(50),
    damageMillionsDollarsTotal VARCHAR(50),
    housesDestroyedTotal VARCHAR(50),
    injuriesTotal VARCHAR(50),
    missingTotal VARCHAR(50),
    date TIMESTAMP,
    id INTEGER PRIMARY KEY,
    latitude DOUBLE PRECISION,
    month INTEGER,
    day INTEGER,
    deaths VARCHAR(50),
    deathsAmountOrder VARCHAR(50),
    deathsAmountOrderTotal INTEGER,
    deathsTotal INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE volcanoes (
    country VARCHAR(100),
    elevation INTEGER,
    id INTEGER PRIMARY KEY,
    latitude FLOAT,
    location VARCHAR(255),
    longitude FLOAT,
    morphology VARCHAR(255),
    name VARCHAR(255) NOT NULL,
    position_type VARCHAR(50),
    region VARCHAR(255),
    status VARCHAR(50),
    timeErupt VARCHAR(255),
    newNum INTEGER,
    num VARCHAR(50),
    objectId INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);