FROM apache/hop:2.15.0

USER root

# Installa Docker CLI e docker-compose plugin
RUN apk add --no-cache docker-cli docker-cli-compose

#COPY ./../../docker-compose.yml /project/docker-compose.yml

USER hop